name: CD

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    uses: vergil-project/vergil-actions/.github/workflows/cd-docs.yml@v2.0
    permissions:
      contents: write
