name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      run-security:
        type: boolean
        default: true
      run-release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    uses: vergil-project/vergil-actions/.github/workflows/ci-audit.yml@v2.0
    with:
      language: shell
      versions: '["latest"]'
      container-suffix: base

  quality:
    uses: vergil-project/vergil-actions/.github/workflows/ci-quality.yml@v2.0
    with:
      language: shell
      versions: '["latest"]'
      container-tag: 'latest'
      container-suffix: base

  security:
    uses: vergil-project/vergil-actions/.github/workflows/ci-security.yml@v2.0
    permissions:
      contents: read
      security-events: write
    with:
      language: shell
      run-standards: ${{ inputs.run-release != 'false' }}
      run-security: ${{ inputs.run-security != 'false' }}
      run-codeql: false
      container-tag: 'latest'
      container-suffix: base

  test:
    uses: vergil-project/vergil-actions/.github/workflows/ci-test.yml@v2.0
    with:
      language: shell
      versions: '["latest"]'
      container-suffix: base

  version:
    uses: vergil-project/vergil-actions/.github/workflows/ci-version-bump.yml@v2.0
    with:
      language: shell
      run-release: ${{ inputs.run-release != 'false' }}
      container-tag: 'latest'
      container-suffix: base
